# Generated by Django 4.2.4 on 2023-09-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_reportcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='rank',
            new_name='student_rank',
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
