# Generated by Django 4.2.4 on 2023-09-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_rename_rank_reportcard_student_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report_card_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
