# Generated by Django 4.2.4 on 2023-09-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_recipe_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
